version: "3.9"
services:

    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_USER=${PG_USERNAME}
            - POSTGRES_DB=${PG_DATABASE}
        container_name: postgres-db
        volumes:
          - ../pgdata:/var/lib/postgresql/data
    product:
      build: 
        context: .
        dockerfile: ./Dockerfile
      image: yaserahmadi/micro-product:latest
      environment: 
        - NODE_ENV=${NODE_ENV}
        - PG_HOST=${PG_HOST_DOCKER}
        - PG_PORT=${PG_PORT}
        - PG_USERNAME=${PG_USERNAME}
        - PG_PASSWORD=${PG_PASSWORD}
        - PG_DATABASE=${PG_DATABASE}
        - SERVER_PORT=${SERVER_PORT}

        - RABBITMQ_HOST=${RABBITMQ_HOST} # rabbitmq host
        - RABBITMQ_PORT=${RABBITMQ_PORT} # rabbitmq port
      ports: 
        - "3000:${SERVER_PORT}"
      container_name: product
      depends_on: 
        - postgres
        - rabbitmq
      volumes: 
        - .:/app
        - /app/node_modules 


    rabbitmq:
      image: rabbitmq:3.10-rc-management-alpine
      ports:
        - "5672:5672" # AMQP protocol port
        - "15672:15672" # HTTP management UI
      container_name: rabbitmq